# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='likes',
        ),
    ]
