# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0002_remove_box_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
