# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-11 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0007_remove_like_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='box',
            name='dis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='box',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
